language: python
python:
   - "3.4"

install: pip install -r requirements.txt

script:
  - coverage run --source=pycep_correios setup.py test

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
